export type themesType =
  | 'a11y-dark'
  | 'atom-dark'
  | 'base16-ateliersulphurpool.light'
  | 'cb'
  | 'darcula'
  | 'default'
  | 'dracula'
  | 'duotone-dark'
  | 'duotone-earth'
  | 'duotone-forest'
  | 'duotone-light'
  | 'duotone-sea'
  | 'duotone-space'
  | 'ghcolors'
  | 'hopscotch'
  | 'material-dark'
  | 'material-light'
  | 'material-oceanic'
  | 'nord'
  | 'pojoaque'
  | 'shades-of-purple'
  | 'synthwave84'
  | 'vs'
  | 'vsc-dark-plus'
  | 'xonokai';

export type langsType =
  | 'auto'
  | 'c'
  | 'css'
  | 'cpp'
  | 'go'
  | 'html'
  | 'java'
  | 'javascript'
  | 'jsx'
  | 'php'
  | 'python'
  | 'rust'
  | 'typescript';

export type fontsType =
  | 'MonoLisa'
  | 'Anonymouse-Pro'
  | 'Cascadia-Code'
  | 'Droid-Sans-Mono'
  | 'Fantasque-Sans-Mono'
  | 'Fira-Code'
  | 'Hack'
  | 'IBM-Flex-Mono'
  | 'Inconsolata'
  | 'JetBrains-Mono'
  | 'Monoid'
  | 'Source-Code-Pro'
  | 'Space-Mono'
  | 'Ubuntu-Mono';
